### ISSUE TITLE
Create the landing page for the Law and Policy Sources

### ISSUE THREAD

**Issue by jhung** [fluid-project/lcil#16]
The landing page for the law and policy sources should:
* list existing law and policy sources
* provide a way to search the name
* provide a way to specify jurisdiction information as a pre-search filter (#17)
* page through search results
* create a new law and policy source

![image](https://user-images.githubusercontent.com/564762/160460655-04816407-59c9-4b10-9f73-c42f4c95dca6.png)

**Comment by jobara** [comment]
Route info:

- `/sources`
  - **Description:** Display an index of law and policy sources
  - **HTTP Method:** `GET`
  - **CRUD Operation:** Read
  - **RESTful Action:** Index
