### ISSUE TITLE
Implement Regime Assessment landing page

### ISSUE THREAD

**Issue by jhung** [fluid-project/lcil#18]
Create the regime assessment landing page so the user can:
* search existing regime assessments (related to #17)
* view details of a regime assessment
* go to edit details of a regime assessment if they have permissions (#19)
* page through search results
* go to create a new regime assessment

![image](https://user-images.githubusercontent.com/564762/160468042-e3092cb8-ab80-4f60-b243-94bc7fc45ce1.png)

**Comment by jobara** [comment]
Route info:

- `/assessments`
  - **Description:** Display an index of Regime Assessments
  - **HTTP Method:** `GET`
  - **CRUD Operation:** Read
  - **RESTful Action:** Index
